// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf C++ Version: 5.29.3

#include "test.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Inner_pb::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : a_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Inner_pb::Inner_pb(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Inner_pbDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Inner_pbDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Inner_pbDefaultTypeInternal() {}
  union {
    Inner_pb _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Inner_pbDefaultTypeInternal _Inner_pb_default_instance_;

inline constexpr Test_pb::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        map_{},
        s_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        optional_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        inner_{nullptr},
        i64_{::int64_t{0}},
        i32_{0},
        ui32_{0u},
        ui64_{::uint64_t{0u}},
        d_{0},
        f_{0},
        oneof_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Test_pb::Test_pb(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Test_pbDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Test_pbDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Test_pbDefaultTypeInternal() {}
  union {
    Test_pb _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Test_pbDefaultTypeInternal _Test_pb_default_instance_;
// ===================================================================

class Inner_pb::_Internal {
 public:
};

Inner_pb::Inner_pb(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Inner_pb)
}
Inner_pb::Inner_pb(
    ::google::protobuf::Arena* arena, const Inner_pb& from)
    : Inner_pb(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Inner_pb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Inner_pb::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.a_ = {};
}
Inner_pb::~Inner_pb() {
  // @@protoc_insertion_point(destructor:Inner_pb)
  SharedDtor(*this);
}
inline void Inner_pb::SharedDtor(MessageLite& self) {
  Inner_pb& this_ = static_cast<Inner_pb&>(self);
  this_._internal_metadata_.Delete<std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Inner_pb::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Inner_pb(arena);
}
constexpr auto Inner_pb::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Inner_pb),
                                            alignof(Inner_pb));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<9> Inner_pb::_class_data_ = {
    {
        &_Inner_pb_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Inner_pb::MergeImpl,
        ::google::protobuf::MessageLite::GetNewImpl<Inner_pb>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Inner_pb::SharedDtor,
        ::google::protobuf::MessageLite::GetClearImpl<Inner_pb>(), &Inner_pb::ByteSizeLong,
            &Inner_pb::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Inner_pb, _impl_._cached_size_),
        true,
    },
    "Inner_pb",
};
const ::google::protobuf::internal::ClassData* Inner_pb::GetClassData() const {
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> Inner_pb::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Inner_pb>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 a = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Inner_pb, _impl_.a_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 a = 1;
    {PROTOBUF_FIELD_OFFSET(Inner_pb, _impl_.a_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Inner_pb::Clear() {
// @@protoc_insertion_point(message_clear_start:Inner_pb)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_ = 0;
  _internal_metadata_.Clear<std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Inner_pb::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Inner_pb& this_ = static_cast<const Inner_pb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Inner_pb::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Inner_pb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Inner_pb)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 a = 1;
          if (this_._internal_a() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_a(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target = stream->WriteRaw(
                this_._internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
                static_cast<int>(this_._internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Inner_pb)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Inner_pb::ByteSizeLong(const MessageLite& base) {
          const Inner_pb& this_ = static_cast<const Inner_pb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Inner_pb::ByteSizeLong() const {
          const Inner_pb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Inner_pb)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 a = 1;
            if (this_._internal_a() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_a());
            }
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            total_size += this_._internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
          }
          this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
          return total_size;
        }

void Inner_pb::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Inner_pb*>(&to_msg);
  auto& from = static_cast<const Inner_pb&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Inner_pb)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_a() != 0) {
    _this->_impl_.a_ = from._impl_.a_;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Inner_pb::CopyFrom(const Inner_pb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Inner_pb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Inner_pb::InternalSwap(Inner_pb* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.a_, other->_impl_.a_);
}

// ===================================================================

// ===================================================================

class Test_pb::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Test_pb>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Test_pb, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Test_pb, _impl_._oneof_case_);
};

Test_pb::Test_pb(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Test_pb)
}
inline PROTOBUF_NDEBUG_INLINE Test_pb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Test_pb& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        map_{visibility, arena, from.map_},
        s_(arena, from.s_),
        optional_(arena, from.optional_),
        oneof_{},
        _oneof_case_{from._oneof_case_[0]} {}

Test_pb::Test_pb(
    ::google::protobuf::Arena* arena,
    const Test_pb& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Test_pb* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.inner_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::MessageLite::CopyConstruct<::Inner_pb>(
                              arena, *from._impl_.inner_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, i64_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, i64_),
           offsetof(Impl_, f_) -
               offsetof(Impl_, i64_) +
               sizeof(Impl_::f_));
  switch (oneof_case()) {
    case ONEOF_NOT_SET:
      break;
      case kOneof1:
        _impl_.oneof_.oneof1_ = from._impl_.oneof_.oneof1_;
        break;
      case kOneof2:
        _impl_.oneof_.oneof2_ = from._impl_.oneof_.oneof2_;
        break;
      case kOneof3:
        new (&_impl_.oneof_.oneof3_) decltype(_impl_.oneof_.oneof3_){arena, from._impl_.oneof_.oneof3_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Test_pb)
}
inline PROTOBUF_NDEBUG_INLINE Test_pb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        map_{visibility, arena},
        s_(arena),
        optional_(arena),
        oneof_{},
        _oneof_case_{} {}

inline void Test_pb::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, inner_),
           0,
           offsetof(Impl_, f_) -
               offsetof(Impl_, inner_) +
               sizeof(Impl_::f_));
}
Test_pb::~Test_pb() {
  // @@protoc_insertion_point(destructor:Test_pb)
  SharedDtor(*this);
}
inline void Test_pb::SharedDtor(MessageLite& self) {
  Test_pb& this_ = static_cast<Test_pb&>(self);
  this_._internal_metadata_.Delete<std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.s_.Destroy();
  this_._impl_.optional_.Destroy();
  delete this_._impl_.inner_;
  if (this_.has_oneof()) {
    this_.clear_oneof();
  }
  this_._impl_.~Impl_();
}

void Test_pb::clear_oneof() {
// @@protoc_insertion_point(one_of_clear_start:Test_pb)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (oneof_case()) {
    case kOneof1: {
      // No need to clear
      break;
    }
    case kOneof2: {
      // No need to clear
      break;
    }
    case kOneof3: {
      _impl_.oneof_.oneof3_.Destroy();
      break;
    }
    case ONEOF_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ONEOF_NOT_SET;
}


inline void* Test_pb::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Test_pb(arena);
}
constexpr auto Test_pb::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.map_) +
          decltype(Test_pb::_impl_.map_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Test_pb), alignof(Test_pb), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Test_pb::PlacementNew_,
                                 sizeof(Test_pb),
                                 alignof(Test_pb));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<8> Test_pb::_class_data_ = {
    {
        &_Test_pb_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Test_pb::MergeImpl,
        ::google::protobuf::MessageLite::GetNewImpl<Test_pb>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Test_pb::SharedDtor,
        ::google::protobuf::MessageLite::GetClearImpl<Test_pb>(), &Test_pb::ByteSizeLong,
            &Test_pb::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Test_pb, _impl_._cached_size_),
        true,
    },
    "Test_pb",
};
const ::google::protobuf::internal::ClassData* Test_pb::GetClassData() const {
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 13, 2, 42, 2> Test_pb::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Test_pb, _impl_._has_bits_),
    0, // no _extensions_
    13, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294959104,  // skipmap
    offsetof(decltype(_table_), field_entries),
    13,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Test_pb>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 i32 = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.i32_)}},
    // int64 i64 = 2;
    {::_pbi::TcParser::FastV64S1,
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.i64_)}},
    // uint32 ui32 = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.ui32_)}},
    // uint64 ui64 = 4;
    {::_pbi::TcParser::FastV64S1,
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.ui64_)}},
    // string s = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.s_)}},
    // float f = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 63, 0, PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.f_)}},
    // double d = 7;
    {::_pbi::TcParser::FastF64S1,
     {57, 63, 0, PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.d_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional string optional = 12;
    {::_pbi::TcParser::FastUS1,
     {98, 0, 0, PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.optional_)}},
    // .Inner_pb inner = 13;
    {::_pbi::TcParser::FastMtS1,
     {106, 1, 0, PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.inner_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 i32 = 1;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.i32_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 i64 = 2;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.i64_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // uint32 ui32 = 3;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.ui32_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint64 ui64 = 4;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.ui64_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string s = 5;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.s_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float f = 6;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.f_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // double d = 7;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.d_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // map<int32, string> map = 8;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.map_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // int32 oneof1 = 9;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.oneof_.oneof1_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt32)},
    // double oneof2 = 10;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.oneof_.oneof2_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
    // string oneof3 = 11;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.oneof_.oneof3_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string optional = 12;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.optional_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .Inner_pb inner = 13;
    {PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.inner_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Inner_pb>()},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(Test_pb()._impl_.map_)>(
        1, 0, 0, 5,
        9)},
  }}, {{
    "\7\0\0\0\0\1\0\0\3\0\0\6\10\0\0\0"
    "Test_pb"
    "s"
    "map"
    "oneof3"
    "optional"
  }},
};

PROTOBUF_NOINLINE void Test_pb::Clear() {
// @@protoc_insertion_point(message_clear_start:Test_pb)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.map_.Clear();
  _impl_.s_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.optional_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.inner_ != nullptr);
      _impl_.inner_->Clear();
    }
  }
  ::memset(&_impl_.i64_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.f_) -
      reinterpret_cast<char*>(&_impl_.i64_)) + sizeof(_impl_.f_));
  clear_oneof();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Test_pb::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Test_pb& this_ = static_cast<const Test_pb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Test_pb::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Test_pb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Test_pb)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 i32 = 1;
          if (this_._internal_i32() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_i32(), target);
          }

          // int64 i64 = 2;
          if (this_._internal_i64() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_i64(), target);
          }

          // uint32 ui32 = 3;
          if (this_._internal_ui32() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_ui32(), target);
          }

          // uint64 ui64 = 4;
          if (this_._internal_ui64() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                4, this_._internal_ui64(), target);
          }

          // string s = 5;
          if (!this_._internal_s().empty()) {
            const std::string& _s = this_._internal_s();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Test_pb.s");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // float f = 6;
          if (::absl::bit_cast<::uint32_t>(this_._internal_f()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                6, this_._internal_f(), target);
          }

          // double d = 7;
          if (::absl::bit_cast<::uint64_t>(this_._internal_d()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                7, this_._internal_d(), target);
          }

          // map<int32, string> map = 8;
          if (!this_._internal_map().empty()) {
            using MapType = ::google::protobuf::Map<::int32_t, std::string>;
            using WireHelper = _pbi::MapEntryFuncs<::int32_t, std::string,
                                           _pbi::WireFormatLite::TYPE_INT32,
                                           _pbi::WireFormatLite::TYPE_STRING>;
            const auto& field = this_._internal_map();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    8, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Test_pb.map");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    8, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Test_pb.map");
              }
            }
          }

          switch (this_.oneof_case()) {
            case kOneof1: {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<9>(
                      stream, this_._internal_oneof1(), target);
              break;
            }
            case kOneof2: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                  10, this_._internal_oneof2(), target);
              break;
            }
            case kOneof3: {
              const std::string& _s = this_._internal_oneof3();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Test_pb.oneof3");
              target = stream->WriteStringMaybeAliased(11, _s, target);
              break;
            }
            default:
              break;
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string optional = 12;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_optional();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Test_pb.optional");
            target = stream->WriteStringMaybeAliased(12, _s, target);
          }

          // .Inner_pb inner = 13;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                13, *this_._impl_.inner_, this_._impl_.inner_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target = stream->WriteRaw(
                this_._internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
                static_cast<int>(this_._internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Test_pb)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Test_pb::ByteSizeLong(const MessageLite& base) {
          const Test_pb& this_ = static_cast<const Test_pb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Test_pb::ByteSizeLong() const {
          const Test_pb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Test_pb)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<int32, string> map = 8;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_map_size());
              for (const auto& entry : this_._internal_map()) {
                total_size += _pbi::MapEntryFuncs<::int32_t, std::string,
                                               _pbi::WireFormatLite::TYPE_INT32,
                                               _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string s = 5;
            if (!this_._internal_s().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_s());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional string optional = 12;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_optional());
            }
            // .Inner_pb inner = 13;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.inner_);
            }
          }
           {
            // int64 i64 = 2;
            if (this_._internal_i64() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_i64());
            }
            // int32 i32 = 1;
            if (this_._internal_i32() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_i32());
            }
            // uint32 ui32 = 3;
            if (this_._internal_ui32() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_ui32());
            }
            // uint64 ui64 = 4;
            if (this_._internal_ui64() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_ui64());
            }
            // double d = 7;
            if (::absl::bit_cast<::uint64_t>(this_._internal_d()) != 0) {
              total_size += 9;
            }
            // float f = 6;
            if (::absl::bit_cast<::uint32_t>(this_._internal_f()) != 0) {
              total_size += 5;
            }
          }
          switch (this_.oneof_case()) {
            // int32 oneof1 = 9;
            case kOneof1: {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_oneof1());
              break;
            }
            // double oneof2 = 10;
            case kOneof2: {
              total_size += 9;
              break;
            }
            // string oneof3 = 11;
            case kOneof3: {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_oneof3());
              break;
            }
            case ONEOF_NOT_SET: {
              break;
            }
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            total_size += this_._internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
          }
          this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
          return total_size;
        }

void Test_pb::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Test_pb*>(&to_msg);
  auto& from = static_cast<const Test_pb&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Test_pb)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.map_.MergeFrom(from._impl_.map_);
  if (!from._internal_s().empty()) {
    _this->_internal_set_s(from._internal_s());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_optional(from._internal_optional());
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.inner_ != nullptr);
      if (_this->_impl_.inner_ == nullptr) {
        _this->_impl_.inner_ =
            ::google::protobuf::MessageLite::CopyConstruct<::Inner_pb>(arena, *from._impl_.inner_);
      } else {
        _this->_impl_.inner_->MergeFrom(*from._impl_.inner_);
      }
    }
  }
  if (from._internal_i64() != 0) {
    _this->_impl_.i64_ = from._impl_.i64_;
  }
  if (from._internal_i32() != 0) {
    _this->_impl_.i32_ = from._impl_.i32_;
  }
  if (from._internal_ui32() != 0) {
    _this->_impl_.ui32_ = from._impl_.ui32_;
  }
  if (from._internal_ui64() != 0) {
    _this->_impl_.ui64_ = from._impl_.ui64_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_d()) != 0) {
    _this->_impl_.d_ = from._impl_.d_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_f()) != 0) {
    _this->_impl_.f_ = from._impl_.f_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_oneof();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kOneof1: {
        _this->_impl_.oneof_.oneof1_ = from._impl_.oneof_.oneof1_;
        break;
      }
      case kOneof2: {
        _this->_impl_.oneof_.oneof2_ = from._impl_.oneof_.oneof2_;
        break;
      }
      case kOneof3: {
        if (oneof_needs_init) {
          _this->_impl_.oneof_.oneof3_.InitDefault();
        }
        _this->_impl_.oneof_.oneof3_.Set(from._internal_oneof3(), arena);
        break;
      }
      case ONEOF_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Test_pb::CopyFrom(const Test_pb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Test_pb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Test_pb::InternalSwap(Test_pb* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.map_.InternalSwap(&other->_impl_.map_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.s_, &other->_impl_.s_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.optional_, &other->_impl_.optional_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.f_)
      + sizeof(Test_pb::_impl_.f_)
      - PROTOBUF_FIELD_OFFSET(Test_pb, _impl_.inner_)>(
          reinterpret_cast<char*>(&_impl_.inner_),
          reinterpret_cast<char*>(&other->_impl_.inner_));
  swap(_impl_.oneof_, other->_impl_.oneof_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
