// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: compat_v2.proto
// Protobuf C++ Version: 5.29.3

#ifndef compat_5fv2_2eproto_2epb_2eh
#define compat_5fv2_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_compat_5fv2_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_compat_5fv2_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_compat_5fv2_2eproto;
class CompatV2;
struct CompatV2DefaultTypeInternal;
extern CompatV2DefaultTypeInternal _CompatV2_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class CompatV2 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CompatV2) */ {
 public:
  inline CompatV2() : CompatV2(nullptr) {}
  ~CompatV2() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CompatV2* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CompatV2));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CompatV2(
      ::google::protobuf::internal::ConstantInitialized);

  inline CompatV2(const CompatV2& from) : CompatV2(nullptr, from) {}
  inline CompatV2(CompatV2&& from) noexcept
      : CompatV2(nullptr, std::move(from)) {}
  inline CompatV2& operator=(const CompatV2& from) {
    CopyFrom(from);
    return *this;
  }
  inline CompatV2& operator=(CompatV2&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CompatV2& default_instance() {
    return *internal_default_instance();
  }
  static inline const CompatV2* internal_default_instance() {
    return reinterpret_cast<const CompatV2*>(
        &_CompatV2_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CompatV2& a, CompatV2& b) { a.Swap(&b); }
  inline void Swap(CompatV2* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CompatV2* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CompatV2* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CompatV2>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CompatV2& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CompatV2& from) { CompatV2::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CompatV2* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CompatV2"; }

 protected:
  explicit CompatV2(::google::protobuf::Arena* arena);
  CompatV2(::google::protobuf::Arena* arena, const CompatV2& from);
  CompatV2(::google::protobuf::Arena* arena, CompatV2&& from) noexcept
      : CompatV2(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBFieldNumber = 2,
    kDFieldNumber = 1002,
    kCFieldNumber = 1001,
    kAFieldNumber = 1,
  };
  // string b = 2;
  void clear_b() ;
  const std::string& b() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_b(Arg_&& arg, Args_... args);
  std::string* mutable_b();
  PROTOBUF_NODISCARD std::string* release_b();
  void set_allocated_b(std::string* value);

  private:
  const std::string& _internal_b() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_b(
      const std::string& value);
  std::string* _internal_mutable_b();

  public:
  // bytes d = 1002;
  void clear_d() ;
  const std::string& d() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_d(Arg_&& arg, Args_... args);
  std::string* mutable_d();
  PROTOBUF_NODISCARD std::string* release_d();
  void set_allocated_d(std::string* value);

  private:
  const std::string& _internal_d() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_d(
      const std::string& value);
  std::string* _internal_mutable_d();

  public:
  // int64 c = 1001;
  void clear_c() ;
  ::int64_t c() const;
  void set_c(::int64_t value);

  private:
  ::int64_t _internal_c() const;
  void _internal_set_c(::int64_t value);

  public:
  // int32 a = 1;
  void clear_a() ;
  ::int32_t a() const;
  void set_a(::int32_t value);

  private:
  ::int32_t _internal_a() const;
  void _internal_set_a(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CompatV2)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 4, 0,
      18, 7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CompatV2& from_msg);
    ::google::protobuf::internal::ArenaStringPtr b_;
    ::google::protobuf::internal::ArenaStringPtr d_;
    ::int64_t c_;
    ::int32_t a_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_compat_5fv2_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CompatV2

// int32 a = 1;
inline void CompatV2::clear_a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.a_ = 0;
}
inline ::int32_t CompatV2::a() const {
  // @@protoc_insertion_point(field_get:CompatV2.a)
  return _internal_a();
}
inline void CompatV2::set_a(::int32_t value) {
  _internal_set_a(value);
  // @@protoc_insertion_point(field_set:CompatV2.a)
}
inline ::int32_t CompatV2::_internal_a() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.a_;
}
inline void CompatV2::_internal_set_a(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.a_ = value;
}

// string b = 2;
inline void CompatV2::clear_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.ClearToEmpty();
}
inline const std::string& CompatV2::b() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CompatV2.b)
  return _internal_b();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void CompatV2::set_b(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CompatV2.b)
}
inline std::string* CompatV2::mutable_b() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_b();
  // @@protoc_insertion_point(field_mutable:CompatV2.b)
  return _s;
}
inline const std::string& CompatV2::_internal_b() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.b_.Get();
}
inline void CompatV2::_internal_set_b(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.Set(value, GetArena());
}
inline std::string* CompatV2::_internal_mutable_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.b_.Mutable( GetArena());
}
inline std::string* CompatV2::release_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CompatV2.b)
  return _impl_.b_.Release();
}
inline void CompatV2::set_allocated_b(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.b_.IsDefault()) {
    _impl_.b_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CompatV2.b)
}

// int64 c = 1001;
inline void CompatV2::clear_c() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_ = ::int64_t{0};
}
inline ::int64_t CompatV2::c() const {
  // @@protoc_insertion_point(field_get:CompatV2.c)
  return _internal_c();
}
inline void CompatV2::set_c(::int64_t value) {
  _internal_set_c(value);
  // @@protoc_insertion_point(field_set:CompatV2.c)
}
inline ::int64_t CompatV2::_internal_c() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.c_;
}
inline void CompatV2::_internal_set_c(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_ = value;
}

// bytes d = 1002;
inline void CompatV2::clear_d() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.d_.ClearToEmpty();
}
inline const std::string& CompatV2::d() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CompatV2.d)
  return _internal_d();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void CompatV2::set_d(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.d_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CompatV2.d)
}
inline std::string* CompatV2::mutable_d() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_d();
  // @@protoc_insertion_point(field_mutable:CompatV2.d)
  return _s;
}
inline const std::string& CompatV2::_internal_d() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.d_.Get();
}
inline void CompatV2::_internal_set_d(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.d_.Set(value, GetArena());
}
inline std::string* CompatV2::_internal_mutable_d() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.d_.Mutable( GetArena());
}
inline std::string* CompatV2::release_d() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CompatV2.d)
  return _impl_.d_.Release();
}
inline void CompatV2::set_allocated_d(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.d_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.d_.IsDefault()) {
    _impl_.d_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CompatV2.d)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // compat_5fv2_2eproto_2epb_2eh
