// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: compat_v2.proto
// Protobuf C++ Version: 5.29.3

#include "compat_v2.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CompatV2::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : b_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        d_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        c_{::int64_t{0}},
        a_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CompatV2::CompatV2(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CompatV2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR CompatV2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CompatV2DefaultTypeInternal() {}
  union {
    CompatV2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CompatV2DefaultTypeInternal _CompatV2_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_compat_5fv2_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_compat_5fv2_2eproto = nullptr;
const ::uint32_t
    TableStruct_compat_5fv2_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::CompatV2, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::CompatV2, _impl_.a_),
        PROTOBUF_FIELD_OFFSET(::CompatV2, _impl_.b_),
        PROTOBUF_FIELD_OFFSET(::CompatV2, _impl_.c_),
        PROTOBUF_FIELD_OFFSET(::CompatV2, _impl_.d_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::CompatV2)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_CompatV2_default_instance_._instance,
};
const char descriptor_table_protodef_compat_5fv2_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017compat_v2.proto\"8\n\010CompatV2\022\t\n\001a\030\001 \001(\005"
    "\022\t\n\001b\030\002 \001(\t\022\n\n\001c\030\351\007 \001(\003\022\n\n\001d\030\352\007 \001(\014b\006pro"
    "to3"
};
static ::absl::once_flag descriptor_table_compat_5fv2_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_compat_5fv2_2eproto = {
    false,
    false,
    83,
    descriptor_table_protodef_compat_5fv2_2eproto,
    "compat_v2.proto",
    &descriptor_table_compat_5fv2_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_compat_5fv2_2eproto::offsets,
    file_level_enum_descriptors_compat_5fv2_2eproto,
    file_level_service_descriptors_compat_5fv2_2eproto,
};
// ===================================================================

class CompatV2::_Internal {
 public:
};

CompatV2::CompatV2(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CompatV2)
}
inline PROTOBUF_NDEBUG_INLINE CompatV2::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::CompatV2& from_msg)
      : b_(arena, from.b_),
        d_(arena, from.d_),
        _cached_size_{0} {}

CompatV2::CompatV2(
    ::google::protobuf::Arena* arena,
    const CompatV2& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CompatV2* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, c_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, c_),
           offsetof(Impl_, a_) -
               offsetof(Impl_, c_) +
               sizeof(Impl_::a_));

  // @@protoc_insertion_point(copy_constructor:CompatV2)
}
inline PROTOBUF_NDEBUG_INLINE CompatV2::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : b_(arena),
        d_(arena),
        _cached_size_{0} {}

inline void CompatV2::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, c_),
           0,
           offsetof(Impl_, a_) -
               offsetof(Impl_, c_) +
               sizeof(Impl_::a_));
}
CompatV2::~CompatV2() {
  // @@protoc_insertion_point(destructor:CompatV2)
  SharedDtor(*this);
}
inline void CompatV2::SharedDtor(MessageLite& self) {
  CompatV2& this_ = static_cast<CompatV2&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.b_.Destroy();
  this_._impl_.d_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CompatV2::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CompatV2(arena);
}
constexpr auto CompatV2::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CompatV2),
                                            alignof(CompatV2));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CompatV2::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CompatV2_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CompatV2::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CompatV2>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CompatV2::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CompatV2>(), &CompatV2::ByteSizeLong,
            &CompatV2::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CompatV2, _impl_._cached_size_),
        false,
    },
    &CompatV2::kDescriptorMethods,
    &descriptor_table_compat_5fv2_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CompatV2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 4, 0, 18, 7> CompatV2::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1002, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CompatV2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string b = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CompatV2, _impl_.b_)}},
    // int32 a = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CompatV2, _impl_.a_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CompatV2, _impl_.a_)}},
  }}, {{
    1001, 0, 1,
    65532, 2,
    65535, 65535
  }}, {{
    // int32 a = 1;
    {PROTOBUF_FIELD_OFFSET(CompatV2, _impl_.a_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string b = 2;
    {PROTOBUF_FIELD_OFFSET(CompatV2, _impl_.b_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 c = 1001;
    {PROTOBUF_FIELD_OFFSET(CompatV2, _impl_.c_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bytes d = 1002;
    {PROTOBUF_FIELD_OFFSET(CompatV2, _impl_.d_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\10\0\1\0\0\0\0\0"
    "CompatV2"
    "b"
  }},
};

PROTOBUF_NOINLINE void CompatV2::Clear() {
// @@protoc_insertion_point(message_clear_start:CompatV2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.b_.ClearToEmpty();
  _impl_.d_.ClearToEmpty();
  ::memset(&_impl_.c_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.a_) -
      reinterpret_cast<char*>(&_impl_.c_)) + sizeof(_impl_.a_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CompatV2::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CompatV2& this_ = static_cast<const CompatV2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CompatV2::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CompatV2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:CompatV2)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 a = 1;
          if (this_._internal_a() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_a(), target);
          }

          // string b = 2;
          if (!this_._internal_b().empty()) {
            const std::string& _s = this_._internal_b();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CompatV2.b");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int64 c = 1001;
          if (this_._internal_c() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt64ToArray(
                1001, this_._internal_c(), target);
          }

          // bytes d = 1002;
          if (!this_._internal_d().empty()) {
            const std::string& _s = this_._internal_d();
            target = stream->WriteBytesMaybeAliased(1002, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:CompatV2)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CompatV2::ByteSizeLong(const MessageLite& base) {
          const CompatV2& this_ = static_cast<const CompatV2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CompatV2::ByteSizeLong() const {
          const CompatV2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:CompatV2)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string b = 2;
            if (!this_._internal_b().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_b());
            }
            // bytes d = 1002;
            if (!this_._internal_d().empty()) {
              total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_d());
            }
            // int64 c = 1001;
            if (this_._internal_c() != 0) {
              total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                              this_._internal_c());
            }
            // int32 a = 1;
            if (this_._internal_a() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_a());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CompatV2::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CompatV2*>(&to_msg);
  auto& from = static_cast<const CompatV2&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CompatV2)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_b().empty()) {
    _this->_internal_set_b(from._internal_b());
  }
  if (!from._internal_d().empty()) {
    _this->_internal_set_d(from._internal_d());
  }
  if (from._internal_c() != 0) {
    _this->_impl_.c_ = from._impl_.c_;
  }
  if (from._internal_a() != 0) {
    _this->_impl_.a_ = from._impl_.a_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CompatV2::CopyFrom(const CompatV2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CompatV2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CompatV2::InternalSwap(CompatV2* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.b_, &other->_impl_.b_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.d_, &other->_impl_.d_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CompatV2, _impl_.a_)
      + sizeof(CompatV2::_impl_.a_)
      - PROTOBUF_FIELD_OFFSET(CompatV2, _impl_.c_)>(
          reinterpret_cast<char*>(&_impl_.c_),
          reinterpret_cast<char*>(&other->_impl_.c_));
}

::google::protobuf::Metadata CompatV2::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_compat_5fv2_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
