// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: defaults.proto
// Protobuf C++ Version: 5.29.3

#include "defaults.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Defaults::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : s_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        by_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        i32_{0},
        b_{false},
        d_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Defaults::Defaults(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DefaultsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DefaultsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DefaultsDefaultTypeInternal() {}
  union {
    Defaults _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DefaultsDefaultTypeInternal _Defaults_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_defaults_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_defaults_2eproto = nullptr;
const ::uint32_t
    TableStruct_defaults_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Defaults, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Defaults, _impl_.i32_),
        PROTOBUF_FIELD_OFFSET(::Defaults, _impl_.b_),
        PROTOBUF_FIELD_OFFSET(::Defaults, _impl_.s_),
        PROTOBUF_FIELD_OFFSET(::Defaults, _impl_.by_),
        PROTOBUF_FIELD_OFFSET(::Defaults, _impl_.d_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Defaults)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Defaults_default_instance_._instance,
};
const char descriptor_table_protodef_defaults_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016defaults.proto\"D\n\010Defaults\022\013\n\003i32\030\001 \001("
    "\005\022\t\n\001b\030\002 \001(\010\022\t\n\001s\030\003 \001(\t\022\n\n\002by\030\004 \001(\014\022\t\n\001d"
    "\030\005 \001(\001b\006proto3"
};
static ::absl::once_flag descriptor_table_defaults_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_defaults_2eproto = {
    false,
    false,
    94,
    descriptor_table_protodef_defaults_2eproto,
    "defaults.proto",
    &descriptor_table_defaults_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_defaults_2eproto::offsets,
    file_level_enum_descriptors_defaults_2eproto,
    file_level_service_descriptors_defaults_2eproto,
};
// ===================================================================

class Defaults::_Internal {
 public:
};

Defaults::Defaults(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Defaults)
}
inline PROTOBUF_NDEBUG_INLINE Defaults::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Defaults& from_msg)
      : s_(arena, from.s_),
        by_(arena, from.by_),
        _cached_size_{0} {}

Defaults::Defaults(
    ::google::protobuf::Arena* arena,
    const Defaults& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Defaults* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, i32_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, i32_),
           offsetof(Impl_, d_) -
               offsetof(Impl_, i32_) +
               sizeof(Impl_::d_));

  // @@protoc_insertion_point(copy_constructor:Defaults)
}
inline PROTOBUF_NDEBUG_INLINE Defaults::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : s_(arena),
        by_(arena),
        _cached_size_{0} {}

inline void Defaults::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, i32_),
           0,
           offsetof(Impl_, d_) -
               offsetof(Impl_, i32_) +
               sizeof(Impl_::d_));
}
Defaults::~Defaults() {
  // @@protoc_insertion_point(destructor:Defaults)
  SharedDtor(*this);
}
inline void Defaults::SharedDtor(MessageLite& self) {
  Defaults& this_ = static_cast<Defaults&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.s_.Destroy();
  this_._impl_.by_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Defaults::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Defaults(arena);
}
constexpr auto Defaults::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Defaults),
                                            alignof(Defaults));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Defaults::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Defaults_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Defaults::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Defaults>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Defaults::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Defaults>(), &Defaults::ByteSizeLong,
            &Defaults::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Defaults, _impl_._cached_size_),
        false,
    },
    &Defaults::kDescriptorMethods,
    &descriptor_table_defaults_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Defaults::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 18, 2> Defaults::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Defaults>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 i32 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Defaults, _impl_.i32_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Defaults, _impl_.i32_)}},
    // bool b = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Defaults, _impl_.b_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Defaults, _impl_.b_)}},
    // string s = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Defaults, _impl_.s_)}},
    // bytes by = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Defaults, _impl_.by_)}},
    // double d = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 63, 0, PROTOBUF_FIELD_OFFSET(Defaults, _impl_.d_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 i32 = 1;
    {PROTOBUF_FIELD_OFFSET(Defaults, _impl_.i32_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool b = 2;
    {PROTOBUF_FIELD_OFFSET(Defaults, _impl_.b_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string s = 3;
    {PROTOBUF_FIELD_OFFSET(Defaults, _impl_.s_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes by = 4;
    {PROTOBUF_FIELD_OFFSET(Defaults, _impl_.by_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // double d = 5;
    {PROTOBUF_FIELD_OFFSET(Defaults, _impl_.d_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\10\0\0\1\0\0\0\0"
    "Defaults"
    "s"
  }},
};

PROTOBUF_NOINLINE void Defaults::Clear() {
// @@protoc_insertion_point(message_clear_start:Defaults)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.s_.ClearToEmpty();
  _impl_.by_.ClearToEmpty();
  ::memset(&_impl_.i32_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.d_) -
      reinterpret_cast<char*>(&_impl_.i32_)) + sizeof(_impl_.d_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Defaults::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Defaults& this_ = static_cast<const Defaults&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Defaults::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Defaults& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Defaults)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 i32 = 1;
          if (this_._internal_i32() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_i32(), target);
          }

          // bool b = 2;
          if (this_._internal_b() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_b(), target);
          }

          // string s = 3;
          if (!this_._internal_s().empty()) {
            const std::string& _s = this_._internal_s();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Defaults.s");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // bytes by = 4;
          if (!this_._internal_by().empty()) {
            const std::string& _s = this_._internal_by();
            target = stream->WriteBytesMaybeAliased(4, _s, target);
          }

          // double d = 5;
          if (::absl::bit_cast<::uint64_t>(this_._internal_d()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                5, this_._internal_d(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Defaults)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Defaults::ByteSizeLong(const MessageLite& base) {
          const Defaults& this_ = static_cast<const Defaults&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Defaults::ByteSizeLong() const {
          const Defaults& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Defaults)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string s = 3;
            if (!this_._internal_s().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_s());
            }
            // bytes by = 4;
            if (!this_._internal_by().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_by());
            }
            // int32 i32 = 1;
            if (this_._internal_i32() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_i32());
            }
            // bool b = 2;
            if (this_._internal_b() != 0) {
              total_size += 2;
            }
            // double d = 5;
            if (::absl::bit_cast<::uint64_t>(this_._internal_d()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Defaults::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Defaults*>(&to_msg);
  auto& from = static_cast<const Defaults&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Defaults)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_s().empty()) {
    _this->_internal_set_s(from._internal_s());
  }
  if (!from._internal_by().empty()) {
    _this->_internal_set_by(from._internal_by());
  }
  if (from._internal_i32() != 0) {
    _this->_impl_.i32_ = from._impl_.i32_;
  }
  if (from._internal_b() != 0) {
    _this->_impl_.b_ = from._impl_.b_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_d()) != 0) {
    _this->_impl_.d_ = from._impl_.d_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Defaults::CopyFrom(const Defaults& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Defaults)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Defaults::InternalSwap(Defaults* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.s_, &other->_impl_.s_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.by_, &other->_impl_.by_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Defaults, _impl_.d_)
      + sizeof(Defaults::_impl_.d_)
      - PROTOBUF_FIELD_OFFSET(Defaults, _impl_.i32_)>(
          reinterpret_cast<char*>(&_impl_.i32_),
          reinterpret_cast<char*>(&other->_impl_.i32_));
}

::google::protobuf::Metadata Defaults::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_defaults_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
