// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: maps_scalars.proto
// Protobuf C++ Version: 5.29.3

#include "maps_scalars.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
              template <typename>
PROTOBUF_CONSTEXPR MapsScalars_MU32S32Entry_DoNotUse::MapsScalars_MU32S32Entry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : MapsScalars_MU32S32Entry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : MapsScalars_MU32S32Entry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct MapsScalars_MU32S32Entry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapsScalars_MU32S32Entry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapsScalars_MU32S32Entry_DoNotUseDefaultTypeInternal() {}
  union {
    MapsScalars_MU32S32Entry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapsScalars_MU32S32Entry_DoNotUseDefaultTypeInternal _MapsScalars_MU32S32Entry_DoNotUse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR MapsScalars_MStrI32Entry_DoNotUse::MapsScalars_MStrI32Entry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : MapsScalars_MStrI32Entry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : MapsScalars_MStrI32Entry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct MapsScalars_MStrI32Entry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapsScalars_MStrI32Entry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapsScalars_MStrI32Entry_DoNotUseDefaultTypeInternal() {}
  union {
    MapsScalars_MStrI32Entry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapsScalars_MStrI32Entry_DoNotUseDefaultTypeInternal _MapsScalars_MStrI32Entry_DoNotUse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR MapsScalars_MI64U64Entry_DoNotUse::MapsScalars_MI64U64Entry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : MapsScalars_MI64U64Entry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : MapsScalars_MI64U64Entry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct MapsScalars_MI64U64Entry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapsScalars_MI64U64Entry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapsScalars_MI64U64Entry_DoNotUseDefaultTypeInternal() {}
  union {
    MapsScalars_MI64U64Entry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapsScalars_MI64U64Entry_DoNotUseDefaultTypeInternal _MapsScalars_MI64U64Entry_DoNotUse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR MapsScalars_MI32StrEntry_DoNotUse::MapsScalars_MI32StrEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : MapsScalars_MI32StrEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : MapsScalars_MI32StrEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct MapsScalars_MI32StrEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapsScalars_MI32StrEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapsScalars_MI32StrEntry_DoNotUseDefaultTypeInternal() {}
  union {
    MapsScalars_MI32StrEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapsScalars_MI32StrEntry_DoNotUseDefaultTypeInternal _MapsScalars_MI32StrEntry_DoNotUse_default_instance_;

inline constexpr MapsScalars::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : m_str_i32_{},
        m_i32_str_{},
        m_i64_u64_{},
        m_u32_s32_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MapsScalars::MapsScalars(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MapsScalarsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapsScalarsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapsScalarsDefaultTypeInternal() {}
  union {
    MapsScalars _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapsScalarsDefaultTypeInternal _MapsScalars_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_maps_5fscalars_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_maps_5fscalars_2eproto = nullptr;
const ::uint32_t
    TableStruct_maps_5fscalars_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MStrI32Entry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MStrI32Entry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MStrI32Entry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MStrI32Entry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MI32StrEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MI32StrEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MI32StrEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MI32StrEntry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MI64U64Entry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MI64U64Entry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MI64U64Entry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MI64U64Entry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MU32S32Entry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MU32S32Entry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MU32S32Entry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars_MU32S32Entry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MapsScalars, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapsScalars, _impl_.m_str_i32_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars, _impl_.m_i32_str_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars, _impl_.m_i64_u64_),
        PROTOBUF_FIELD_OFFSET(::MapsScalars, _impl_.m_u32_s32_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::MapsScalars_MStrI32Entry_DoNotUse)},
        {12, 22, -1, sizeof(::MapsScalars_MI32StrEntry_DoNotUse)},
        {24, 34, -1, sizeof(::MapsScalars_MI64U64Entry_DoNotUse)},
        {36, 46, -1, sizeof(::MapsScalars_MU32S32Entry_DoNotUse)},
        {48, -1, -1, sizeof(::MapsScalars)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_MapsScalars_MStrI32Entry_DoNotUse_default_instance_._instance,
    &::_MapsScalars_MI32StrEntry_DoNotUse_default_instance_._instance,
    &::_MapsScalars_MI64U64Entry_DoNotUse_default_instance_._instance,
    &::_MapsScalars_MU32S32Entry_DoNotUse_default_instance_._instance,
    &::_MapsScalars_default_instance_._instance,
};
const char descriptor_table_protodef_maps_5fscalars_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022maps_scalars.proto\"\205\003\n\013MapsScalars\022,\n\t"
    "m_str_i32\030\001 \003(\0132\031.MapsScalars.MStrI32Ent"
    "ry\022,\n\tm_i32_str\030\002 \003(\0132\031.MapsScalars.MI32"
    "StrEntry\022,\n\tm_i64_u64\030\003 \003(\0132\031.MapsScalar"
    "s.MI64U64Entry\022,\n\tm_u32_s32\030\004 \003(\0132\031.Maps"
    "Scalars.MU32S32Entry\032.\n\014MStrI32Entry\022\013\n\003"
    "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\032.\n\014MI32StrE"
    "ntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\t:\0028\001\032.\n\014"
    "MI64U64Entry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001(\004"
    ":\0028\001\032.\n\014MU32S32Entry\022\013\n\003key\030\001 \001(\r\022\r\n\005val"
    "ue\030\002 \001(\021:\0028\001b\006proto3"
};
static ::absl::once_flag descriptor_table_maps_5fscalars_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_maps_5fscalars_2eproto = {
    false,
    false,
    420,
    descriptor_table_protodef_maps_5fscalars_2eproto,
    "maps_scalars.proto",
    &descriptor_table_maps_5fscalars_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_maps_5fscalars_2eproto::offsets,
    file_level_enum_descriptors_maps_5fscalars_2eproto,
    file_level_service_descriptors_maps_5fscalars_2eproto,
};
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              MapsScalars_MStrI32Entry_DoNotUse::MapsScalars_MStrI32Entry_DoNotUse() : SuperType(_class_data_.base()) {}
              MapsScalars_MStrI32Entry_DoNotUse::MapsScalars_MStrI32Entry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              MapsScalars_MStrI32Entry_DoNotUse::MapsScalars_MStrI32Entry_DoNotUse() : SuperType() {}
              MapsScalars_MStrI32Entry_DoNotUse::MapsScalars_MStrI32Entry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* MapsScalars_MStrI32Entry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) MapsScalars_MStrI32Entry_DoNotUse(arena);
              }
              constexpr auto MapsScalars_MStrI32Entry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MapsScalars_MStrI32Entry_DoNotUse),
                                                          alignof(MapsScalars_MStrI32Entry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull MapsScalars_MStrI32Entry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_MapsScalars_MStrI32Entry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &MapsScalars_MStrI32Entry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<MapsScalars_MStrI32Entry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &MapsScalars_MStrI32Entry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &MapsScalars_MStrI32Entry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(MapsScalars_MStrI32Entry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &MapsScalars_MStrI32Entry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_maps_5fscalars_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* MapsScalars_MStrI32Entry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 36, 2> MapsScalars_MStrI32Entry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MapsScalars_MStrI32Entry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapsScalars_MStrI32Entry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MapsScalars_MStrI32Entry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MapsScalars_MStrI32Entry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MapsScalars_MStrI32Entry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(MapsScalars_MStrI32Entry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 value = 2;
    {PROTOBUF_FIELD_OFFSET(MapsScalars_MStrI32Entry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\30\3\0\0\0\0\0\0"
    "MapsScalars.MStrI32Entry"
    "key"
  }},
};

// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              MapsScalars_MI32StrEntry_DoNotUse::MapsScalars_MI32StrEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              MapsScalars_MI32StrEntry_DoNotUse::MapsScalars_MI32StrEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              MapsScalars_MI32StrEntry_DoNotUse::MapsScalars_MI32StrEntry_DoNotUse() : SuperType() {}
              MapsScalars_MI32StrEntry_DoNotUse::MapsScalars_MI32StrEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* MapsScalars_MI32StrEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) MapsScalars_MI32StrEntry_DoNotUse(arena);
              }
              constexpr auto MapsScalars_MI32StrEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MapsScalars_MI32StrEntry_DoNotUse),
                                                          alignof(MapsScalars_MI32StrEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull MapsScalars_MI32StrEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_MapsScalars_MI32StrEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &MapsScalars_MI32StrEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<MapsScalars_MI32StrEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &MapsScalars_MI32StrEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &MapsScalars_MI32StrEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(MapsScalars_MI32StrEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &MapsScalars_MI32StrEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_maps_5fscalars_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* MapsScalars_MI32StrEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2> MapsScalars_MI32StrEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MapsScalars_MI32StrEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapsScalars_MI32StrEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(MapsScalars_MI32StrEntry_DoNotUse, _impl_.value_)}},
    // int32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MapsScalars_MI32StrEntry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MapsScalars_MI32StrEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 key = 1;
    {PROTOBUF_FIELD_OFFSET(MapsScalars_MI32StrEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(MapsScalars_MI32StrEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\0\5\0\0\0\0\0"
    "MapsScalars.MI32StrEntry"
    "value"
  }},
};

// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              MapsScalars_MI64U64Entry_DoNotUse::MapsScalars_MI64U64Entry_DoNotUse() : SuperType(_class_data_.base()) {}
              MapsScalars_MI64U64Entry_DoNotUse::MapsScalars_MI64U64Entry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              MapsScalars_MI64U64Entry_DoNotUse::MapsScalars_MI64U64Entry_DoNotUse() : SuperType() {}
              MapsScalars_MI64U64Entry_DoNotUse::MapsScalars_MI64U64Entry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* MapsScalars_MI64U64Entry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) MapsScalars_MI64U64Entry_DoNotUse(arena);
              }
              constexpr auto MapsScalars_MI64U64Entry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MapsScalars_MI64U64Entry_DoNotUse),
                                                          alignof(MapsScalars_MI64U64Entry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull MapsScalars_MI64U64Entry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_MapsScalars_MI64U64Entry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &MapsScalars_MI64U64Entry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<MapsScalars_MI64U64Entry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &MapsScalars_MI64U64Entry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &MapsScalars_MI64U64Entry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(MapsScalars_MI64U64Entry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &MapsScalars_MI64U64Entry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_maps_5fscalars_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* MapsScalars_MI64U64Entry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> MapsScalars_MI64U64Entry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MapsScalars_MI64U64Entry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapsScalars_MI64U64Entry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MapsScalars_MI64U64Entry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MapsScalars_MI64U64Entry_DoNotUse, _impl_.value_)}},
    // int64 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MapsScalars_MI64U64Entry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MapsScalars_MI64U64Entry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 key = 1;
    {PROTOBUF_FIELD_OFFSET(MapsScalars_MI64U64Entry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // uint64 value = 2;
    {PROTOBUF_FIELD_OFFSET(MapsScalars_MI64U64Entry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              MapsScalars_MU32S32Entry_DoNotUse::MapsScalars_MU32S32Entry_DoNotUse() : SuperType(_class_data_.base()) {}
              MapsScalars_MU32S32Entry_DoNotUse::MapsScalars_MU32S32Entry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              MapsScalars_MU32S32Entry_DoNotUse::MapsScalars_MU32S32Entry_DoNotUse() : SuperType() {}
              MapsScalars_MU32S32Entry_DoNotUse::MapsScalars_MU32S32Entry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* MapsScalars_MU32S32Entry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) MapsScalars_MU32S32Entry_DoNotUse(arena);
              }
              constexpr auto MapsScalars_MU32S32Entry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MapsScalars_MU32S32Entry_DoNotUse),
                                                          alignof(MapsScalars_MU32S32Entry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull MapsScalars_MU32S32Entry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_MapsScalars_MU32S32Entry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &MapsScalars_MU32S32Entry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<MapsScalars_MU32S32Entry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &MapsScalars_MU32S32Entry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &MapsScalars_MU32S32Entry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(MapsScalars_MU32S32Entry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &MapsScalars_MU32S32Entry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_maps_5fscalars_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* MapsScalars_MU32S32Entry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> MapsScalars_MU32S32Entry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MapsScalars_MU32S32Entry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapsScalars_MU32S32Entry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // sint32 value = 2;
    {::_pbi::TcParser::FastZ32S1,
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MapsScalars_MU32S32Entry_DoNotUse, _impl_.value_)}},
    // uint32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MapsScalars_MU32S32Entry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MapsScalars_MU32S32Entry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 key = 1;
    {PROTOBUF_FIELD_OFFSET(MapsScalars_MU32S32Entry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // sint32 value = 2;
    {PROTOBUF_FIELD_OFFSET(MapsScalars_MU32S32Entry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kSInt32)},
  }},
  // no aux_entries
  {{
  }},
};

// ===================================================================

class MapsScalars::_Internal {
 public:
};

MapsScalars::MapsScalars(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MapsScalars)
}
inline PROTOBUF_NDEBUG_INLINE MapsScalars::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MapsScalars& from_msg)
      : m_str_i32_{visibility, arena, from.m_str_i32_},
        m_i32_str_{visibility, arena, from.m_i32_str_},
        m_i64_u64_{visibility, arena, from.m_i64_u64_},
        m_u32_s32_{visibility, arena, from.m_u32_s32_},
        _cached_size_{0} {}

MapsScalars::MapsScalars(
    ::google::protobuf::Arena* arena,
    const MapsScalars& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MapsScalars* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:MapsScalars)
}
inline PROTOBUF_NDEBUG_INLINE MapsScalars::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : m_str_i32_{visibility, arena},
        m_i32_str_{visibility, arena},
        m_i64_u64_{visibility, arena},
        m_u32_s32_{visibility, arena},
        _cached_size_{0} {}

inline void MapsScalars::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MapsScalars::~MapsScalars() {
  // @@protoc_insertion_point(destructor:MapsScalars)
  SharedDtor(*this);
}
inline void MapsScalars::SharedDtor(MessageLite& self) {
  MapsScalars& this_ = static_cast<MapsScalars&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* MapsScalars::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MapsScalars(arena);
}
constexpr auto MapsScalars::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_str_i32_) +
          decltype(MapsScalars::_impl_.m_str_i32_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_str_i32_) +
          decltype(MapsScalars::_impl_.m_str_i32_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_i32_str_) +
          decltype(MapsScalars::_impl_.m_i32_str_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_i32_str_) +
          decltype(MapsScalars::_impl_.m_i32_str_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_i64_u64_) +
          decltype(MapsScalars::_impl_.m_i64_u64_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_i64_u64_) +
          decltype(MapsScalars::_impl_.m_i64_u64_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_u32_s32_) +
          decltype(MapsScalars::_impl_.m_u32_s32_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_u32_s32_) +
          decltype(MapsScalars::_impl_.m_u32_s32_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(MapsScalars), alignof(MapsScalars), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&MapsScalars::PlacementNew_,
                                 sizeof(MapsScalars),
                                 alignof(MapsScalars));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MapsScalars::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MapsScalars_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MapsScalars::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MapsScalars>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MapsScalars::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MapsScalars>(), &MapsScalars::ByteSizeLong,
            &MapsScalars::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_._cached_size_),
        false,
    },
    &MapsScalars::kDescriptorMethods,
    &descriptor_table_maps_5fscalars_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MapsScalars::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 4, 4, 38, 2> MapsScalars::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapsScalars>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, int32> m_str_i32 = 1;
    {PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_str_i32_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // map<int32, string> m_i32_str = 2;
    {PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_i32_str_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // map<int64, uint64> m_i64_u64 = 3;
    {PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_i64_u64_), 0, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // map<uint32, sint32> m_u32_s32 = 4;
    {PROTOBUF_FIELD_OFFSET(MapsScalars, _impl_.m_u32_s32_), 0, 3,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(MapsScalars()._impl_.m_str_i32_)>(
        1, 0, 0, 9,
        5)},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(MapsScalars()._impl_.m_i32_str_)>(
        1, 0, 0, 5,
        9)},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(MapsScalars()._impl_.m_i64_u64_)>(
        0, 0, 0, 3,
        4)},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(MapsScalars()._impl_.m_u32_s32_)>(
        0, 0, 0, 13,
        17)},
  }}, {{
    "\13\11\11\0\0\0\0\0"
    "MapsScalars"
    "m_str_i32"
    "m_i32_str"
  }},
};

PROTOBUF_NOINLINE void MapsScalars::Clear() {
// @@protoc_insertion_point(message_clear_start:MapsScalars)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.m_str_i32_.Clear();
  _impl_.m_i32_str_.Clear();
  _impl_.m_i64_u64_.Clear();
  _impl_.m_u32_s32_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MapsScalars::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MapsScalars& this_ = static_cast<const MapsScalars&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MapsScalars::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MapsScalars& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MapsScalars)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // map<string, int32> m_str_i32 = 1;
          if (!this_._internal_m_str_i32().empty()) {
            using MapType = ::google::protobuf::Map<std::string, ::int32_t>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, ::int32_t,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_INT32>;
            const auto& field = this_._internal_m_str_i32();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    1, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MapsScalars.m_str_i32");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    1, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MapsScalars.m_str_i32");
              }
            }
          }

          // map<int32, string> m_i32_str = 2;
          if (!this_._internal_m_i32_str().empty()) {
            using MapType = ::google::protobuf::Map<::int32_t, std::string>;
            using WireHelper = _pbi::MapEntryFuncs<::int32_t, std::string,
                                           _pbi::WireFormatLite::TYPE_INT32,
                                           _pbi::WireFormatLite::TYPE_STRING>;
            const auto& field = this_._internal_m_i32_str();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MapsScalars.m_i32_str");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MapsScalars.m_i32_str");
              }
            }
          }

          // map<int64, uint64> m_i64_u64 = 3;
          if (!this_._internal_m_i64_u64().empty()) {
            using MapType = ::google::protobuf::Map<::int64_t, ::uint64_t>;
            using WireHelper = _pbi::MapEntryFuncs<::int64_t, ::uint64_t,
                                           _pbi::WireFormatLite::TYPE_INT64,
                                           _pbi::WireFormatLite::TYPE_UINT64>;
            const auto& field = this_._internal_m_i64_u64();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    3, entry.first, entry.second, target, stream);
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    3, entry.first, entry.second, target, stream);
              }
            }
          }

          // map<uint32, sint32> m_u32_s32 = 4;
          if (!this_._internal_m_u32_s32().empty()) {
            using MapType = ::google::protobuf::Map<::uint32_t, ::int32_t>;
            using WireHelper = _pbi::MapEntryFuncs<::uint32_t, ::int32_t,
                                           _pbi::WireFormatLite::TYPE_UINT32,
                                           _pbi::WireFormatLite::TYPE_SINT32>;
            const auto& field = this_._internal_m_u32_s32();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    4, entry.first, entry.second, target, stream);
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    4, entry.first, entry.second, target, stream);
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MapsScalars)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MapsScalars::ByteSizeLong(const MessageLite& base) {
          const MapsScalars& this_ = static_cast<const MapsScalars&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MapsScalars::ByteSizeLong() const {
          const MapsScalars& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MapsScalars)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, int32> m_str_i32 = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_m_str_i32_size());
              for (const auto& entry : this_._internal_m_str_i32()) {
                total_size += _pbi::MapEntryFuncs<std::string, ::int32_t,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_INT32>::ByteSizeLong(entry.first, entry.second);
              }
            }
            // map<int32, string> m_i32_str = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_m_i32_str_size());
              for (const auto& entry : this_._internal_m_i32_str()) {
                total_size += _pbi::MapEntryFuncs<::int32_t, std::string,
                                               _pbi::WireFormatLite::TYPE_INT32,
                                               _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
              }
            }
            // map<int64, uint64> m_i64_u64 = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_m_i64_u64_size());
              for (const auto& entry : this_._internal_m_i64_u64()) {
                total_size += _pbi::MapEntryFuncs<::int64_t, ::uint64_t,
                                               _pbi::WireFormatLite::TYPE_INT64,
                                               _pbi::WireFormatLite::TYPE_UINT64>::ByteSizeLong(entry.first, entry.second);
              }
            }
            // map<uint32, sint32> m_u32_s32 = 4;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_m_u32_s32_size());
              for (const auto& entry : this_._internal_m_u32_s32()) {
                total_size += _pbi::MapEntryFuncs<::uint32_t, ::int32_t,
                                               _pbi::WireFormatLite::TYPE_UINT32,
                                               _pbi::WireFormatLite::TYPE_SINT32>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MapsScalars::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MapsScalars*>(&to_msg);
  auto& from = static_cast<const MapsScalars&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MapsScalars)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.m_str_i32_.MergeFrom(from._impl_.m_str_i32_);
  _this->_impl_.m_i32_str_.MergeFrom(from._impl_.m_i32_str_);
  _this->_impl_.m_i64_u64_.MergeFrom(from._impl_.m_i64_u64_);
  _this->_impl_.m_u32_s32_.MergeFrom(from._impl_.m_u32_s32_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MapsScalars::CopyFrom(const MapsScalars& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MapsScalars)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MapsScalars::InternalSwap(MapsScalars* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.m_str_i32_.InternalSwap(&other->_impl_.m_str_i32_);
  _impl_.m_i32_str_.InternalSwap(&other->_impl_.m_i32_str_);
  _impl_.m_i64_u64_.InternalSwap(&other->_impl_.m_i64_u64_);
  _impl_.m_u32_s32_.InternalSwap(&other->_impl_.m_u32_s32_);
}

::google::protobuf::Metadata MapsScalars::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_maps_5fscalars_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
