// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: maps_messages.proto
// Protobuf C++ Version: 5.29.3

#ifndef maps_5fmessages_2eproto_2epb_2eh
#define maps_5fmessages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_maps_5fmessages_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_maps_5fmessages_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_maps_5fmessages_2eproto;
class InnerVal;
struct InnerValDefaultTypeInternal;
extern InnerValDefaultTypeInternal _InnerVal_default_instance_;
class MapsMessages;
struct MapsMessagesDefaultTypeInternal;
extern MapsMessagesDefaultTypeInternal _MapsMessages_default_instance_;
class MapsMessages_MI32MsgEntry_DoNotUse;
struct MapsMessages_MI32MsgEntry_DoNotUseDefaultTypeInternal;
extern MapsMessages_MI32MsgEntry_DoNotUseDefaultTypeInternal _MapsMessages_MI32MsgEntry_DoNotUse_default_instance_;
class MapsMessages_MI64InnerEntry_DoNotUse;
struct MapsMessages_MI64InnerEntry_DoNotUseDefaultTypeInternal;
extern MapsMessages_MI64InnerEntry_DoNotUseDefaultTypeInternal _MapsMessages_MI64InnerEntry_DoNotUse_default_instance_;
class MapsMessages_MStrMsgEntry_DoNotUse;
struct MapsMessages_MStrMsgEntry_DoNotUseDefaultTypeInternal;
extern MapsMessages_MStrMsgEntry_DoNotUseDefaultTypeInternal _MapsMessages_MStrMsgEntry_DoNotUse_default_instance_;
class Val;
struct ValDefaultTypeInternal;
extern ValDefaultTypeInternal _Val_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Val final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Val) */ {
 public:
  inline Val() : Val(nullptr) {}
  ~Val() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Val* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Val));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Val(
      ::google::protobuf::internal::ConstantInitialized);

  inline Val(const Val& from) : Val(nullptr, from) {}
  inline Val(Val&& from) noexcept
      : Val(nullptr, std::move(from)) {}
  inline Val& operator=(const Val& from) {
    CopyFrom(from);
    return *this;
  }
  inline Val& operator=(Val&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Val& default_instance() {
    return *internal_default_instance();
  }
  static inline const Val* internal_default_instance() {
    return reinterpret_cast<const Val*>(
        &_Val_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Val& a, Val& b) { a.Swap(&b); }
  inline void Swap(Val* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Val* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Val* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Val>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Val& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Val& from) { Val::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Val* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Val"; }

 protected:
  explicit Val(::google::protobuf::Arena* arena);
  Val(::google::protobuf::Arena* arena, const Val& from);
  Val(::google::protobuf::Arena* arena, Val&& from) noexcept
      : Val(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBFieldNumber = 2,
    kAFieldNumber = 1,
  };
  // string b = 2;
  void clear_b() ;
  const std::string& b() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_b(Arg_&& arg, Args_... args);
  std::string* mutable_b();
  PROTOBUF_NODISCARD std::string* release_b();
  void set_allocated_b(std::string* value);

  private:
  const std::string& _internal_b() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_b(
      const std::string& value);
  std::string* _internal_mutable_b();

  public:
  // int32 a = 1;
  void clear_a() ;
  ::int32_t a() const;
  void set_a(::int32_t value);

  private:
  ::int32_t _internal_a() const;
  void _internal_set_a(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Val)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      13, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Val& from_msg);
    ::google::protobuf::internal::ArenaStringPtr b_;
    ::int32_t a_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_maps_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class MapsMessages_MStrMsgEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, ::google::protobuf::Message,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, ::google::protobuf::Message,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  MapsMessages_MStrMsgEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MapsMessages_MStrMsgEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit MapsMessages_MStrMsgEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const MapsMessages_MStrMsgEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const MapsMessages_MStrMsgEntry_DoNotUse*>(
        &_MapsMessages_MStrMsgEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_maps_5fmessages_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      37, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class MapsMessages_MI32MsgEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          ::int32_t, ::google::protobuf::Message,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      ::int32_t, ::google::protobuf::Message,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  MapsMessages_MI32MsgEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MapsMessages_MI32MsgEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit MapsMessages_MI32MsgEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const MapsMessages_MI32MsgEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const MapsMessages_MI32MsgEntry_DoNotUse*>(
        &_MapsMessages_MI32MsgEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_maps_5fmessages_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class InnerVal final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:InnerVal) */ {
 public:
  inline InnerVal() : InnerVal(nullptr) {}
  ~InnerVal() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InnerVal* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InnerVal));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InnerVal(
      ::google::protobuf::internal::ConstantInitialized);

  inline InnerVal(const InnerVal& from) : InnerVal(nullptr, from) {}
  inline InnerVal(InnerVal&& from) noexcept
      : InnerVal(nullptr, std::move(from)) {}
  inline InnerVal& operator=(const InnerVal& from) {
    CopyFrom(from);
    return *this;
  }
  inline InnerVal& operator=(InnerVal&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InnerVal& default_instance() {
    return *internal_default_instance();
  }
  static inline const InnerVal* internal_default_instance() {
    return reinterpret_cast<const InnerVal*>(
        &_InnerVal_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(InnerVal& a, InnerVal& b) { a.Swap(&b); }
  inline void Swap(InnerVal* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InnerVal* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InnerVal* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InnerVal>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InnerVal& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InnerVal& from) { InnerVal::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InnerVal* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "InnerVal"; }

 protected:
  explicit InnerVal(::google::protobuf::Arena* arena);
  InnerVal(::google::protobuf::Arena* arena, const InnerVal& from);
  InnerVal(::google::protobuf::Arena* arena, InnerVal&& from) noexcept
      : InnerVal(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVFieldNumber = 1,
  };
  // .Val v = 1;
  bool has_v() const;
  void clear_v() ;
  const ::Val& v() const;
  PROTOBUF_NODISCARD ::Val* release_v();
  ::Val* mutable_v();
  void set_allocated_v(::Val* value);
  void unsafe_arena_set_allocated_v(::Val* value);
  ::Val* unsafe_arena_release_v();

  private:
  const ::Val& _internal_v() const;
  ::Val* _internal_mutable_v();

  public:
  // @@protoc_insertion_point(class_scope:InnerVal)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const InnerVal& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Val* v_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_maps_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class MapsMessages_MI64InnerEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          ::int64_t, ::google::protobuf::Message,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      ::int64_t, ::google::protobuf::Message,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  MapsMessages_MI64InnerEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MapsMessages_MI64InnerEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit MapsMessages_MI64InnerEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const MapsMessages_MI64InnerEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const MapsMessages_MI64InnerEntry_DoNotUse*>(
        &_MapsMessages_MI64InnerEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_maps_5fmessages_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class MapsMessages final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MapsMessages) */ {
 public:
  inline MapsMessages() : MapsMessages(nullptr) {}
  ~MapsMessages() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MapsMessages* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MapsMessages));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MapsMessages(
      ::google::protobuf::internal::ConstantInitialized);

  inline MapsMessages(const MapsMessages& from) : MapsMessages(nullptr, from) {}
  inline MapsMessages(MapsMessages&& from) noexcept
      : MapsMessages(nullptr, std::move(from)) {}
  inline MapsMessages& operator=(const MapsMessages& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapsMessages& operator=(MapsMessages&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MapsMessages& default_instance() {
    return *internal_default_instance();
  }
  static inline const MapsMessages* internal_default_instance() {
    return reinterpret_cast<const MapsMessages*>(
        &_MapsMessages_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(MapsMessages& a, MapsMessages& b) { a.Swap(&b); }
  inline void Swap(MapsMessages* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapsMessages* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MapsMessages* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MapsMessages>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MapsMessages& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MapsMessages& from) { MapsMessages::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MapsMessages* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "MapsMessages"; }

 protected:
  explicit MapsMessages(::google::protobuf::Arena* arena);
  MapsMessages(::google::protobuf::Arena* arena, const MapsMessages& from);
  MapsMessages(::google::protobuf::Arena* arena, MapsMessages&& from) noexcept
      : MapsMessages(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMStrMsgFieldNumber = 1,
    kMI32MsgFieldNumber = 2,
    kMI64InnerFieldNumber = 3,
  };
  // map<string, .Val> m_str_msg = 1;
  int m_str_msg_size() const;
  private:
  int _internal_m_str_msg_size() const;

  public:
  void clear_m_str_msg() ;
  const ::google::protobuf::Map<std::string, ::Val>& m_str_msg() const;
  ::google::protobuf::Map<std::string, ::Val>* mutable_m_str_msg();

  private:
  const ::google::protobuf::Map<std::string, ::Val>& _internal_m_str_msg() const;
  ::google::protobuf::Map<std::string, ::Val>* _internal_mutable_m_str_msg();

  public:
  // map<int32, .Val> m_i32_msg = 2;
  int m_i32_msg_size() const;
  private:
  int _internal_m_i32_msg_size() const;

  public:
  void clear_m_i32_msg() ;
  const ::google::protobuf::Map<::int32_t, ::Val>& m_i32_msg() const;
  ::google::protobuf::Map<::int32_t, ::Val>* mutable_m_i32_msg();

  private:
  const ::google::protobuf::Map<::int32_t, ::Val>& _internal_m_i32_msg() const;
  ::google::protobuf::Map<::int32_t, ::Val>* _internal_mutable_m_i32_msg();

  public:
  // map<int64, .InnerVal> m_i64_inner = 3;
  int m_i64_inner_size() const;
  private:
  int _internal_m_i64_inner_size() const;

  public:
  void clear_m_i64_inner() ;
  const ::google::protobuf::Map<::int64_t, ::InnerVal>& m_i64_inner() const;
  ::google::protobuf::Map<::int64_t, ::InnerVal>* mutable_m_i64_inner();

  private:
  const ::google::protobuf::Map<::int64_t, ::InnerVal>& _internal_m_i64_inner() const;
  ::google::protobuf::Map<::int64_t, ::InnerVal>* _internal_mutable_m_i64_inner();

  public:
  // @@protoc_insertion_point(class_scope:MapsMessages)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 3, 6,
      30, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MapsMessages& from_msg);
    ::google::protobuf::internal::MapField<MapsMessages_MStrMsgEntry_DoNotUse, std::string, ::Val,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        m_str_msg_;
    ::google::protobuf::internal::MapField<MapsMessages_MI32MsgEntry_DoNotUse, ::int32_t, ::Val,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        m_i32_msg_;
    ::google::protobuf::internal::MapField<MapsMessages_MI64InnerEntry_DoNotUse, ::int64_t, ::InnerVal,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        m_i64_inner_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_maps_5fmessages_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Val

// int32 a = 1;
inline void Val::clear_a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.a_ = 0;
}
inline ::int32_t Val::a() const {
  // @@protoc_insertion_point(field_get:Val.a)
  return _internal_a();
}
inline void Val::set_a(::int32_t value) {
  _internal_set_a(value);
  // @@protoc_insertion_point(field_set:Val.a)
}
inline ::int32_t Val::_internal_a() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.a_;
}
inline void Val::_internal_set_a(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.a_ = value;
}

// string b = 2;
inline void Val::clear_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.ClearToEmpty();
}
inline const std::string& Val::b() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Val.b)
  return _internal_b();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Val::set_b(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Val.b)
}
inline std::string* Val::mutable_b() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_b();
  // @@protoc_insertion_point(field_mutable:Val.b)
  return _s;
}
inline const std::string& Val::_internal_b() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.b_.Get();
}
inline void Val::_internal_set_b(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.Set(value, GetArena());
}
inline std::string* Val::_internal_mutable_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.b_.Mutable( GetArena());
}
inline std::string* Val::release_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Val.b)
  return _impl_.b_.Release();
}
inline void Val::set_allocated_b(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.b_.IsDefault()) {
    _impl_.b_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Val.b)
}

// -------------------------------------------------------------------

// InnerVal

// .Val v = 1;
inline bool InnerVal::has_v() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.v_ != nullptr);
  return value;
}
inline void InnerVal::clear_v() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.v_ != nullptr) _impl_.v_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Val& InnerVal::_internal_v() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Val* p = _impl_.v_;
  return p != nullptr ? *p : reinterpret_cast<const ::Val&>(::_Val_default_instance_);
}
inline const ::Val& InnerVal::v() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:InnerVal.v)
  return _internal_v();
}
inline void InnerVal::unsafe_arena_set_allocated_v(::Val* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.v_);
  }
  _impl_.v_ = reinterpret_cast<::Val*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:InnerVal.v)
}
inline ::Val* InnerVal::release_v() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Val* released = _impl_.v_;
  _impl_.v_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Val* InnerVal::unsafe_arena_release_v() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:InnerVal.v)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Val* temp = _impl_.v_;
  _impl_.v_ = nullptr;
  return temp;
}
inline ::Val* InnerVal::_internal_mutable_v() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.v_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Val>(GetArena());
    _impl_.v_ = reinterpret_cast<::Val*>(p);
  }
  return _impl_.v_;
}
inline ::Val* InnerVal::mutable_v() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Val* _msg = _internal_mutable_v();
  // @@protoc_insertion_point(field_mutable:InnerVal.v)
  return _msg;
}
inline void InnerVal::set_allocated_v(::Val* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.v_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.v_ = reinterpret_cast<::Val*>(value);
  // @@protoc_insertion_point(field_set_allocated:InnerVal.v)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MapsMessages

// map<string, .Val> m_str_msg = 1;
inline int MapsMessages::_internal_m_str_msg_size() const {
  return _internal_m_str_msg().size();
}
inline int MapsMessages::m_str_msg_size() const {
  return _internal_m_str_msg_size();
}
inline void MapsMessages::clear_m_str_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_str_msg_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::Val>& MapsMessages::_internal_m_str_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.m_str_msg_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::Val>& MapsMessages::m_str_msg() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:MapsMessages.m_str_msg)
  return _internal_m_str_msg();
}
inline ::google::protobuf::Map<std::string, ::Val>* MapsMessages::_internal_mutable_m_str_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.m_str_msg_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::Val>* MapsMessages::mutable_m_str_msg() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:MapsMessages.m_str_msg)
  return _internal_mutable_m_str_msg();
}

// map<int32, .Val> m_i32_msg = 2;
inline int MapsMessages::_internal_m_i32_msg_size() const {
  return _internal_m_i32_msg().size();
}
inline int MapsMessages::m_i32_msg_size() const {
  return _internal_m_i32_msg_size();
}
inline void MapsMessages::clear_m_i32_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_i32_msg_.Clear();
}
inline const ::google::protobuf::Map<::int32_t, ::Val>& MapsMessages::_internal_m_i32_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.m_i32_msg_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::Val>& MapsMessages::m_i32_msg() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:MapsMessages.m_i32_msg)
  return _internal_m_i32_msg();
}
inline ::google::protobuf::Map<::int32_t, ::Val>* MapsMessages::_internal_mutable_m_i32_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.m_i32_msg_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::Val>* MapsMessages::mutable_m_i32_msg() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:MapsMessages.m_i32_msg)
  return _internal_mutable_m_i32_msg();
}

// map<int64, .InnerVal> m_i64_inner = 3;
inline int MapsMessages::_internal_m_i64_inner_size() const {
  return _internal_m_i64_inner().size();
}
inline int MapsMessages::m_i64_inner_size() const {
  return _internal_m_i64_inner_size();
}
inline void MapsMessages::clear_m_i64_inner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_i64_inner_.Clear();
}
inline const ::google::protobuf::Map<::int64_t, ::InnerVal>& MapsMessages::_internal_m_i64_inner() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.m_i64_inner_.GetMap();
}
inline const ::google::protobuf::Map<::int64_t, ::InnerVal>& MapsMessages::m_i64_inner() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:MapsMessages.m_i64_inner)
  return _internal_m_i64_inner();
}
inline ::google::protobuf::Map<::int64_t, ::InnerVal>* MapsMessages::_internal_mutable_m_i64_inner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.m_i64_inner_.MutableMap();
}
inline ::google::protobuf::Map<::int64_t, ::InnerVal>* MapsMessages::mutable_m_i64_inner() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:MapsMessages.m_i64_inner)
  return _internal_mutable_m_i64_inner();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // maps_5fmessages_2eproto_2epb_2eh
