// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: optional_presence.proto
// Protobuf C++ Version: 5.29.3

#include "optional_presence.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr OptionalPresence_HasPresence::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OptionalPresence_HasPresence::OptionalPresence_HasPresence(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OptionalPresence_HasPresenceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OptionalPresence_HasPresenceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OptionalPresence_HasPresenceDefaultTypeInternal() {}
  union {
    OptionalPresence_HasPresence _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OptionalPresence_HasPresenceDefaultTypeInternal _OptionalPresence_HasPresence_default_instance_;

inline constexpr OptionalPresence::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        o_string_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msg_{nullptr},
        o_int32_{0},
        o_enum_{static_cast< ::OptEnum >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR OptionalPresence::OptionalPresence(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OptionalPresenceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OptionalPresenceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OptionalPresenceDefaultTypeInternal() {}
  union {
    OptionalPresence _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OptionalPresenceDefaultTypeInternal _OptionalPresence_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_optional_5fpresence_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_optional_5fpresence_2eproto = nullptr;
const ::uint32_t
    TableStruct_optional_5fpresence_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::OptionalPresence_HasPresence, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::OptionalPresence_HasPresence, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::OptionalPresence, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::OptionalPresence, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::OptionalPresence, _impl_.o_int32_),
        PROTOBUF_FIELD_OFFSET(::OptionalPresence, _impl_.o_string_),
        PROTOBUF_FIELD_OFFSET(::OptionalPresence, _impl_.o_enum_),
        PROTOBUF_FIELD_OFFSET(::OptionalPresence, _impl_.msg_),
        2,
        0,
        3,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::OptionalPresence_HasPresence)},
        {9, 21, -1, sizeof(::OptionalPresence)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_OptionalPresence_HasPresence_default_instance_._instance,
    &::_OptionalPresence_default_instance_._instance,
};
const char descriptor_table_protodef_optional_5fpresence_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027optional_presence.proto\"\310\001\n\020OptionalPr"
    "esence\022\024\n\007o_int32\030\001 \001(\005H\000\210\001\001\022\025\n\010o_string"
    "\030\002 \001(\tH\001\210\001\001\022\035\n\006o_enum\030\003 \001(\0162\010.OptEnumH\002\210"
    "\001\001\022*\n\003msg\030\n \001(\0132\035.OptionalPresence.HasPr"
    "esence\032\030\n\013HasPresence\022\t\n\001x\030\001 \001(\005B\n\n\010_o_i"
    "nt32B\013\n\t_o_stringB\t\n\007_o_enum*$\n\007OptEnum\022"
    "\014\n\010OPT_ZERO\020\000\022\013\n\007OPT_ONE\020\001b\006proto3"
};
static ::absl::once_flag descriptor_table_optional_5fpresence_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_optional_5fpresence_2eproto = {
    false,
    false,
    274,
    descriptor_table_protodef_optional_5fpresence_2eproto,
    "optional_presence.proto",
    &descriptor_table_optional_5fpresence_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_optional_5fpresence_2eproto::offsets,
    file_level_enum_descriptors_optional_5fpresence_2eproto,
    file_level_service_descriptors_optional_5fpresence_2eproto,
};
const ::google::protobuf::EnumDescriptor* OptEnum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_optional_5fpresence_2eproto);
  return file_level_enum_descriptors_optional_5fpresence_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t OptEnum_internal_data_[] = {
    131072u, 0u, };
bool OptEnum_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class OptionalPresence_HasPresence::_Internal {
 public:
};

OptionalPresence_HasPresence::OptionalPresence_HasPresence(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:OptionalPresence.HasPresence)
}
OptionalPresence_HasPresence::OptionalPresence_HasPresence(
    ::google::protobuf::Arena* arena, const OptionalPresence_HasPresence& from)
    : OptionalPresence_HasPresence(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE OptionalPresence_HasPresence::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void OptionalPresence_HasPresence::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.x_ = {};
}
OptionalPresence_HasPresence::~OptionalPresence_HasPresence() {
  // @@protoc_insertion_point(destructor:OptionalPresence.HasPresence)
  SharedDtor(*this);
}
inline void OptionalPresence_HasPresence::SharedDtor(MessageLite& self) {
  OptionalPresence_HasPresence& this_ = static_cast<OptionalPresence_HasPresence&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* OptionalPresence_HasPresence::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) OptionalPresence_HasPresence(arena);
}
constexpr auto OptionalPresence_HasPresence::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(OptionalPresence_HasPresence),
                                            alignof(OptionalPresence_HasPresence));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull OptionalPresence_HasPresence::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_OptionalPresence_HasPresence_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &OptionalPresence_HasPresence::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<OptionalPresence_HasPresence>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &OptionalPresence_HasPresence::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<OptionalPresence_HasPresence>(), &OptionalPresence_HasPresence::ByteSizeLong,
            &OptionalPresence_HasPresence::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(OptionalPresence_HasPresence, _impl_._cached_size_),
        false,
    },
    &OptionalPresence_HasPresence::kDescriptorMethods,
    &descriptor_table_optional_5fpresence_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* OptionalPresence_HasPresence::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> OptionalPresence_HasPresence::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::OptionalPresence_HasPresence>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 x = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(OptionalPresence_HasPresence, _impl_.x_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(OptionalPresence_HasPresence, _impl_.x_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 x = 1;
    {PROTOBUF_FIELD_OFFSET(OptionalPresence_HasPresence, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void OptionalPresence_HasPresence::Clear() {
// @@protoc_insertion_point(message_clear_start:OptionalPresence.HasPresence)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.x_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* OptionalPresence_HasPresence::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const OptionalPresence_HasPresence& this_ = static_cast<const OptionalPresence_HasPresence&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* OptionalPresence_HasPresence::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const OptionalPresence_HasPresence& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:OptionalPresence.HasPresence)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 x = 1;
          if (this_._internal_x() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_x(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:OptionalPresence.HasPresence)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t OptionalPresence_HasPresence::ByteSizeLong(const MessageLite& base) {
          const OptionalPresence_HasPresence& this_ = static_cast<const OptionalPresence_HasPresence&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t OptionalPresence_HasPresence::ByteSizeLong() const {
          const OptionalPresence_HasPresence& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:OptionalPresence.HasPresence)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 x = 1;
            if (this_._internal_x() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_x());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void OptionalPresence_HasPresence::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OptionalPresence_HasPresence*>(&to_msg);
  auto& from = static_cast<const OptionalPresence_HasPresence&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OptionalPresence.HasPresence)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_x() != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OptionalPresence_HasPresence::CopyFrom(const OptionalPresence_HasPresence& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OptionalPresence.HasPresence)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OptionalPresence_HasPresence::InternalSwap(OptionalPresence_HasPresence* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.x_, other->_impl_.x_);
}

::google::protobuf::Metadata OptionalPresence_HasPresence::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OptionalPresence::_Internal {
 public:
  using HasBits =
      decltype(std::declval<OptionalPresence>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_._has_bits_);
};

OptionalPresence::OptionalPresence(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:OptionalPresence)
}
inline PROTOBUF_NDEBUG_INLINE OptionalPresence::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::OptionalPresence& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        o_string_(arena, from.o_string_) {}

OptionalPresence::OptionalPresence(
    ::google::protobuf::Arena* arena,
    const OptionalPresence& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OptionalPresence* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.msg_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::OptionalPresence_HasPresence>(
                              arena, *from._impl_.msg_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, o_int32_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, o_int32_),
           offsetof(Impl_, o_enum_) -
               offsetof(Impl_, o_int32_) +
               sizeof(Impl_::o_enum_));

  // @@protoc_insertion_point(copy_constructor:OptionalPresence)
}
inline PROTOBUF_NDEBUG_INLINE OptionalPresence::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        o_string_(arena) {}

inline void OptionalPresence::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, msg_),
           0,
           offsetof(Impl_, o_enum_) -
               offsetof(Impl_, msg_) +
               sizeof(Impl_::o_enum_));
}
OptionalPresence::~OptionalPresence() {
  // @@protoc_insertion_point(destructor:OptionalPresence)
  SharedDtor(*this);
}
inline void OptionalPresence::SharedDtor(MessageLite& self) {
  OptionalPresence& this_ = static_cast<OptionalPresence&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.o_string_.Destroy();
  delete this_._impl_.msg_;
  this_._impl_.~Impl_();
}

inline void* OptionalPresence::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) OptionalPresence(arena);
}
constexpr auto OptionalPresence::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(OptionalPresence),
                                            alignof(OptionalPresence));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull OptionalPresence::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_OptionalPresence_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &OptionalPresence::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<OptionalPresence>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &OptionalPresence::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<OptionalPresence>(), &OptionalPresence::ByteSizeLong,
            &OptionalPresence::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_._cached_size_),
        false,
    },
    &OptionalPresence::kDescriptorMethods,
    &descriptor_table_optional_5fpresence_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* OptionalPresence::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 33, 2> OptionalPresence::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_._has_bits_),
    0, // no _extensions_
    10, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966776,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::OptionalPresence>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 o_int32 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(OptionalPresence, _impl_.o_int32_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_.o_int32_)}},
    // optional string o_string = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_.o_string_)}},
    // optional .OptEnum o_enum = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(OptionalPresence, _impl_.o_enum_), 3>(),
     {24, 3, 0, PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_.o_enum_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 o_int32 = 1;
    {PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_.o_int32_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string o_string = 2;
    {PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_.o_string_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .OptEnum o_enum = 3;
    {PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_.o_enum_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .OptionalPresence.HasPresence msg = 10;
    {PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_.msg_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::OptionalPresence_HasPresence>()},
  }}, {{
    "\20\0\10\0\0\0\0\0"
    "OptionalPresence"
    "o_string"
  }},
};

PROTOBUF_NOINLINE void OptionalPresence::Clear() {
// @@protoc_insertion_point(message_clear_start:OptionalPresence)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.o_string_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.msg_ != nullptr);
      _impl_.msg_->Clear();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    ::memset(&_impl_.o_int32_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.o_enum_) -
        reinterpret_cast<char*>(&_impl_.o_int32_)) + sizeof(_impl_.o_enum_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* OptionalPresence::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const OptionalPresence& this_ = static_cast<const OptionalPresence&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* OptionalPresence::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const OptionalPresence& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:OptionalPresence)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 o_int32 = 1;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_o_int32(), target);
          }

          // optional string o_string = 2;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_o_string();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "OptionalPresence.o_string");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // optional .OptEnum o_enum = 3;
          if (cached_has_bits & 0x00000008u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_o_enum(), target);
          }

          // .OptionalPresence.HasPresence msg = 10;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                10, *this_._impl_.msg_, this_._impl_.msg_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:OptionalPresence)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t OptionalPresence::ByteSizeLong(const MessageLite& base) {
          const OptionalPresence& this_ = static_cast<const OptionalPresence&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t OptionalPresence::ByteSizeLong() const {
          const OptionalPresence& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:OptionalPresence)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x0000000fu) {
            // optional string o_string = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_o_string());
            }
            // .OptionalPresence.HasPresence msg = 10;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.msg_);
            }
            // optional int32 o_int32 = 1;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_o_int32());
            }
            // optional .OptEnum o_enum = 3;
            if (cached_has_bits & 0x00000008u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_o_enum());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void OptionalPresence::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OptionalPresence*>(&to_msg);
  auto& from = static_cast<const OptionalPresence&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:OptionalPresence)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_o_string(from._internal_o_string());
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.msg_ != nullptr);
      if (_this->_impl_.msg_ == nullptr) {
        _this->_impl_.msg_ =
            ::google::protobuf::Message::CopyConstruct<::OptionalPresence_HasPresence>(arena, *from._impl_.msg_);
      } else {
        _this->_impl_.msg_->MergeFrom(*from._impl_.msg_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.o_int32_ = from._impl_.o_int32_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.o_enum_ = from._impl_.o_enum_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OptionalPresence::CopyFrom(const OptionalPresence& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OptionalPresence)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OptionalPresence::InternalSwap(OptionalPresence* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.o_string_, &other->_impl_.o_string_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_.o_enum_)
      + sizeof(OptionalPresence::_impl_.o_enum_)
      - PROTOBUF_FIELD_OFFSET(OptionalPresence, _impl_.msg_)>(
          reinterpret_cast<char*>(&_impl_.msg_),
          reinterpret_cast<char*>(&other->_impl_.msg_));
}

::google::protobuf::Metadata OptionalPresence::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_optional_5fpresence_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
