// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: repeated_scalars.proto
// Protobuf C++ Version: 5.29.3

#include "repeated_scalars.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr RepeatedScalars::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : r_int32_default_packed_{},
        _r_int32_default_packed_cached_byte_size_{0},
        r_sint32_unpacked_{},
        r_fixed32_packed_{},
        r_double_unpacked_{},
        r_enums_default_packed_{},
        _r_enums_default_packed_cached_byte_size_{0},
        r_strings_{},
        r_bytes_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RepeatedScalars::RepeatedScalars(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RepeatedScalarsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RepeatedScalarsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RepeatedScalarsDefaultTypeInternal() {}
  union {
    RepeatedScalars _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RepeatedScalarsDefaultTypeInternal _RepeatedScalars_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_repeated_5fscalars_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_repeated_5fscalars_2eproto = nullptr;
const ::uint32_t
    TableStruct_repeated_5fscalars_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::RepeatedScalars, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::RepeatedScalars, _impl_.r_int32_default_packed_),
        PROTOBUF_FIELD_OFFSET(::RepeatedScalars, _impl_.r_sint32_unpacked_),
        PROTOBUF_FIELD_OFFSET(::RepeatedScalars, _impl_.r_fixed32_packed_),
        PROTOBUF_FIELD_OFFSET(::RepeatedScalars, _impl_.r_double_unpacked_),
        PROTOBUF_FIELD_OFFSET(::RepeatedScalars, _impl_.r_enums_default_packed_),
        PROTOBUF_FIELD_OFFSET(::RepeatedScalars, _impl_.r_strings_),
        PROTOBUF_FIELD_OFFSET(::RepeatedScalars, _impl_.r_bytes_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::RepeatedScalars)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_RepeatedScalars_default_instance_._instance,
};
const char descriptor_table_protodef_repeated_5fscalars_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026repeated_scalars.proto\"\326\001\n\017RepeatedSca"
    "lars\022\036\n\026r_int32_default_packed\030\001 \003(\005\022\035\n\021"
    "r_sint32_unpacked\030\002 \003(\021B\002\020\000\022\030\n\020r_fixed32"
    "_packed\030\003 \003(\007\022\035\n\021r_double_unpacked\030\004 \003(\001"
    "B\002\020\000\022\'\n\026r_enums_default_packed\030\005 \003(\0162\007.R"
    "eEnum\022\021\n\tr_strings\030\006 \003(\t\022\017\n\007r_bytes\030\007 \003("
    "\014**\n\006ReEnum\022\n\n\006R_ZERO\020\000\022\t\n\005R_ONE\020\001\022\t\n\005R_"
    "TWO\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_repeated_5fscalars_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_repeated_5fscalars_2eproto = {
    false,
    false,
    293,
    descriptor_table_protodef_repeated_5fscalars_2eproto,
    "repeated_scalars.proto",
    &descriptor_table_repeated_5fscalars_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_repeated_5fscalars_2eproto::offsets,
    file_level_enum_descriptors_repeated_5fscalars_2eproto,
    file_level_service_descriptors_repeated_5fscalars_2eproto,
};
const ::google::protobuf::EnumDescriptor* ReEnum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_repeated_5fscalars_2eproto);
  return file_level_enum_descriptors_repeated_5fscalars_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ReEnum_internal_data_[] = {
    196608u, 0u, };
bool ReEnum_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class RepeatedScalars::_Internal {
 public:
};

RepeatedScalars::RepeatedScalars(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RepeatedScalars)
}
inline PROTOBUF_NDEBUG_INLINE RepeatedScalars::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::RepeatedScalars& from_msg)
      : r_int32_default_packed_{visibility, arena, from.r_int32_default_packed_},
        _r_int32_default_packed_cached_byte_size_{0},
        r_sint32_unpacked_{visibility, arena, from.r_sint32_unpacked_},
        r_fixed32_packed_{visibility, arena, from.r_fixed32_packed_},
        r_double_unpacked_{visibility, arena, from.r_double_unpacked_},
        r_enums_default_packed_{visibility, arena, from.r_enums_default_packed_},
        _r_enums_default_packed_cached_byte_size_{0},
        r_strings_{visibility, arena, from.r_strings_},
        r_bytes_{visibility, arena, from.r_bytes_},
        _cached_size_{0} {}

RepeatedScalars::RepeatedScalars(
    ::google::protobuf::Arena* arena,
    const RepeatedScalars& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RepeatedScalars* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:RepeatedScalars)
}
inline PROTOBUF_NDEBUG_INLINE RepeatedScalars::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : r_int32_default_packed_{visibility, arena},
        _r_int32_default_packed_cached_byte_size_{0},
        r_sint32_unpacked_{visibility, arena},
        r_fixed32_packed_{visibility, arena},
        r_double_unpacked_{visibility, arena},
        r_enums_default_packed_{visibility, arena},
        _r_enums_default_packed_cached_byte_size_{0},
        r_strings_{visibility, arena},
        r_bytes_{visibility, arena},
        _cached_size_{0} {}

inline void RepeatedScalars::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RepeatedScalars::~RepeatedScalars() {
  // @@protoc_insertion_point(destructor:RepeatedScalars)
  SharedDtor(*this);
}
inline void RepeatedScalars::SharedDtor(MessageLite& self) {
  RepeatedScalars& this_ = static_cast<RepeatedScalars&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* RepeatedScalars::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RepeatedScalars(arena);
}
constexpr auto RepeatedScalars::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_int32_default_packed_) +
          decltype(RepeatedScalars::_impl_.r_int32_default_packed_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_sint32_unpacked_) +
          decltype(RepeatedScalars::_impl_.r_sint32_unpacked_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_fixed32_packed_) +
          decltype(RepeatedScalars::_impl_.r_fixed32_packed_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_double_unpacked_) +
          decltype(RepeatedScalars::_impl_.r_double_unpacked_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_enums_default_packed_) +
          decltype(RepeatedScalars::_impl_.r_enums_default_packed_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_strings_) +
          decltype(RepeatedScalars::_impl_.r_strings_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_bytes_) +
          decltype(RepeatedScalars::_impl_.r_bytes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(RepeatedScalars), alignof(RepeatedScalars), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&RepeatedScalars::PlacementNew_,
                                 sizeof(RepeatedScalars),
                                 alignof(RepeatedScalars));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RepeatedScalars::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RepeatedScalars_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RepeatedScalars::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RepeatedScalars>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RepeatedScalars::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RepeatedScalars>(), &RepeatedScalars::ByteSizeLong,
            &RepeatedScalars::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_._cached_size_),
        false,
    },
    &RepeatedScalars::kDescriptorMethods,
    &descriptor_table_repeated_5fscalars_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RepeatedScalars::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 33, 2> RepeatedScalars::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RepeatedScalars>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated int32 r_int32_default_packed = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_int32_default_packed_)}},
    // repeated sint32 r_sint32_unpacked = 2 [packed = false];
    {::_pbi::TcParser::FastZ32R1,
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_sint32_unpacked_)}},
    // repeated fixed32 r_fixed32_packed = 3;
    {::_pbi::TcParser::FastF32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_fixed32_packed_)}},
    // repeated double r_double_unpacked = 4 [packed = false];
    {::_pbi::TcParser::FastF64R1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_double_unpacked_)}},
    // repeated .ReEnum r_enums_default_packed = 5;
    {::_pbi::TcParser::FastV32P1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_enums_default_packed_)}},
    // repeated string r_strings = 6;
    {::_pbi::TcParser::FastUR1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_strings_)}},
    // repeated bytes r_bytes = 7;
    {::_pbi::TcParser::FastBR1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_bytes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int32 r_int32_default_packed = 1;
    {PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_int32_default_packed_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // repeated sint32 r_sint32_unpacked = 2 [packed = false];
    {PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_sint32_unpacked_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kSInt32)},
    // repeated fixed32 r_fixed32_packed = 3;
    {PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_fixed32_packed_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFixed32)},
    // repeated double r_double_unpacked = 4 [packed = false];
    {PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_double_unpacked_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kDouble)},
    // repeated .ReEnum r_enums_default_packed = 5;
    {PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_enums_default_packed_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedOpenEnum)},
    // repeated string r_strings = 6;
    {PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_strings_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated bytes r_bytes = 7;
    {PROTOBUF_FIELD_OFFSET(RepeatedScalars, _impl_.r_bytes_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\17\0\0\0\0\0\11\0"
    "RepeatedScalars"
    "r_strings"
  }},
};

PROTOBUF_NOINLINE void RepeatedScalars::Clear() {
// @@protoc_insertion_point(message_clear_start:RepeatedScalars)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.r_int32_default_packed_.Clear();
  _impl_.r_sint32_unpacked_.Clear();
  _impl_.r_fixed32_packed_.Clear();
  _impl_.r_double_unpacked_.Clear();
  _impl_.r_enums_default_packed_.Clear();
  _impl_.r_strings_.Clear();
  _impl_.r_bytes_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RepeatedScalars::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RepeatedScalars& this_ = static_cast<const RepeatedScalars&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RepeatedScalars::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RepeatedScalars& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:RepeatedScalars)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated int32 r_int32_default_packed = 1;
          {
            int byte_size = this_._impl_._r_int32_default_packed_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  1, this_._internal_r_int32_default_packed(), byte_size, target);
            }
          }

          // repeated sint32 r_sint32_unpacked = 2 [packed = false];
          for (int i = 0, n = this_._internal_r_sint32_unpacked_size(); i < n; ++i) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
                2, this_._internal_r_sint32_unpacked().Get(i), target);
          }

          // repeated fixed32 r_fixed32_packed = 3;
          if (this_._internal_r_fixed32_packed_size() > 0) {
            target = stream->WriteFixedPacked(3, this_._internal_r_fixed32_packed(), target);
          }

          // repeated double r_double_unpacked = 4 [packed = false];
          for (int i = 0, n = this_._internal_r_double_unpacked_size(); i < n; ++i) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_r_double_unpacked().Get(i), target);
          }

          // repeated .ReEnum r_enums_default_packed = 5;
          {
            std::size_t byte_size =
                                              this_._impl_._r_enums_default_packed_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteEnumPacked(
                  5, this_._internal_r_enums_default_packed(), byte_size, target);
            }
          }

          // repeated string r_strings = 6;
          for (int i = 0, n = this_._internal_r_strings_size(); i < n; ++i) {
            const auto& s = this_._internal_r_strings().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RepeatedScalars.r_strings");
            target = stream->WriteString(6, s, target);
          }

          // repeated bytes r_bytes = 7;
          for (int i = 0, n = this_._internal_r_bytes_size(); i < n; ++i) {
            const auto& s = this_._internal_r_bytes().Get(i);
            target = stream->WriteBytes(7, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:RepeatedScalars)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RepeatedScalars::ByteSizeLong(const MessageLite& base) {
          const RepeatedScalars& this_ = static_cast<const RepeatedScalars&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RepeatedScalars::ByteSizeLong() const {
          const RepeatedScalars& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:RepeatedScalars)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 r_int32_default_packed = 1;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_r_int32_default_packed(), 1,
                      this_._impl_._r_int32_default_packed_cached_byte_size_);
            }
            // repeated sint32 r_sint32_unpacked = 2 [packed = false];
            {
              std::size_t data_size = ::_pbi::WireFormatLite::SInt32Size(
                  this_._internal_r_sint32_unpacked());
              std::size_t tag_size = std::size_t{1} *
                  ::_pbi::FromIntSize(this_._internal_r_sint32_unpacked_size());
              total_size += tag_size + data_size;
            }
            // repeated fixed32 r_fixed32_packed = 3;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_r_fixed32_packed_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
            // repeated double r_double_unpacked = 4 [packed = false];
            {
              std::size_t data_size = std::size_t{8} *
                  ::_pbi::FromIntSize(this_._internal_r_double_unpacked_size());
              std::size_t tag_size = std::size_t{1} *
                  ::_pbi::FromIntSize(this_._internal_r_double_unpacked_size());
              total_size += tag_size + data_size;
            }
            // repeated .ReEnum r_enums_default_packed = 5;
            {
              total_size += ::_pbi::WireFormatLite::EnumSizeWithPackedTagSize(
                  this_._internal_r_enums_default_packed(), 1, this_._impl_._r_enums_default_packed_cached_byte_size_);
            }
            // repeated string r_strings = 6;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_r_strings().size());
              for (int i = 0, n = this_._internal_r_strings().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_r_strings().Get(i));
              }
            }
            // repeated bytes r_bytes = 7;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_r_bytes().size());
              for (int i = 0, n = this_._internal_r_bytes().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
                    this_._internal_r_bytes().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RepeatedScalars::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RepeatedScalars*>(&to_msg);
  auto& from = static_cast<const RepeatedScalars&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RepeatedScalars)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_r_int32_default_packed()->MergeFrom(from._internal_r_int32_default_packed());
  _this->_internal_mutable_r_sint32_unpacked()->MergeFrom(from._internal_r_sint32_unpacked());
  _this->_internal_mutable_r_fixed32_packed()->MergeFrom(from._internal_r_fixed32_packed());
  _this->_internal_mutable_r_double_unpacked()->MergeFrom(from._internal_r_double_unpacked());
  _this->_internal_mutable_r_enums_default_packed()->MergeFrom(from._internal_r_enums_default_packed());
  _this->_internal_mutable_r_strings()->MergeFrom(from._internal_r_strings());
  _this->_internal_mutable_r_bytes()->MergeFrom(from._internal_r_bytes());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RepeatedScalars::CopyFrom(const RepeatedScalars& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RepeatedScalars)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RepeatedScalars::InternalSwap(RepeatedScalars* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.r_int32_default_packed_.InternalSwap(&other->_impl_.r_int32_default_packed_);
  _impl_.r_sint32_unpacked_.InternalSwap(&other->_impl_.r_sint32_unpacked_);
  _impl_.r_fixed32_packed_.InternalSwap(&other->_impl_.r_fixed32_packed_);
  _impl_.r_double_unpacked_.InternalSwap(&other->_impl_.r_double_unpacked_);
  _impl_.r_enums_default_packed_.InternalSwap(&other->_impl_.r_enums_default_packed_);
  _impl_.r_strings_.InternalSwap(&other->_impl_.r_strings_);
  _impl_.r_bytes_.InternalSwap(&other->_impl_.r_bytes_);
}

::google::protobuf::Metadata RepeatedScalars::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_repeated_5fscalars_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
